name: Tests and Lints packages

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.6.0

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up project
        run: |
          pnpm install
          pnpm prisma:gen

      - name: Run linting
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.6.0

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up project
        run: |
          pnpm install
          pnpm prisma:gen

      - name: Run tests
        run: |
          cp .env.ci .env
          pnpm test:silent

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.6.0

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up project
        run: |
          pnpm install
          pnpm prisma:gen

      - name: Run typecheck
        run: pnpm typecheck
